In [2]:
pip install pandas

Requirement already satisfied: pandas in c:\legacyapp\python\python39\lib\site-packages (2.2.0)Note: you may need to restart the kernel to use updated packages.

WARNING: You are using pip version 21.1.3; however, version 23.3.2 is available.
You should consider upgrading via the 'c:\legacyapp\python\python39\python.exe -m pip install --upgrade pip' command.

Requirement already satisfied: tzdata>=2022.7 in c:\legacyapp\python\python39\lib\site-packages (from pandas) (2023.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\legacyapp\python\python39\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\legacyapp\python\python39\lib\site-packages (from pandas) (2023.4)
Requirement already satisfied: numpy<2,>=1.22.4 in c:\legacyapp\python\python39\lib\site-packages (from pandas) (1.26.3)
Requirement already satisfied: six>=1.5 in c:\legacyapp\python\python39\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [3]:
import pandas as pd

C:\Users\uif77660\AppData\Local\Temp\ipykernel_4016\4080736814.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [10]:
match_df=pd.read_csv(filepath_or_buffer="Euro_2012_stats_TEAM.csv")
match_df

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,...,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
0,Croatia,4,13,12,51.9%,16.0%,32,0,0,0,...,13,81.3%,41,62,2,9,0,9,9,16
1,Czech Republic,4,13,18,41.9%,12.9%,39,0,0,0,...,9,60.1%,53,73,8,7,0,11,11,19
2,Denmark,4,10,10,50.0%,20.0%,27,1,0,0,...,10,66.7%,25,38,8,4,0,7,7,15
3,England,5,11,18,50.0%,17.2%,40,0,0,0,...,22,88.1%,43,45,6,5,0,11,11,16
4,France,3,22,24,37.9%,6.5%,65,1,0,0,...,6,54.6%,36,51,5,6,0,11,11,19
5,Germany,10,32,32,47.8%,15.6%,80,2,1,0,...,10,62.6%,63,49,12,4,0,15,15,17
6,Greece,5,8,18,30.7%,19.2%,32,1,1,1,...,13,65.1%,67,48,12,9,1,12,12,20
7,Italy,6,34,45,43.0%,7.5%,110,2,0,0,...,20,74.1%,101,89,16,16,0,18,18,19
8,Netherlands,2,12,36,25.0%,4.1%,60,2,0,0,...,12,70.6%,35,30,3,5,0,7,7,15
9,Poland,2,15,23,39.4%,5.2%,48,0,0,0,...,6,66.7%,48,56,3,7,1,7,7,17
10,Portugal,6,22,42,34.3%,9.3%,82,6,0,0,...,10,71.5%,73,90,10,12,0,14,14,16
11,Republic of Ireland,1,7,12,36.8%,5.2%,28,0,0,0,...,17,65.4%,43,51,11,6,1,10,10,17
12,Russia,5,9,31,22.5%,12.5%,59,2,0,0,...,10,77.0%,34,43,4,6,0,7,7,16
13,Spain,12,42,33,55.9%,16.0%,100,0,1,0,...,15,93.8%,102,83,19,11,0,17,17,18
14,Sweden,5,17,19,47.2%,13.8%,39,3,0,0,...,8,61.6%,35,51,7,7,0,9,9,18
15,Ukraine,2,7,26,21.2%,6.0%,38,0,0,0,...,13,76.5%,48,31,4,5,0,9,9,18

## How to check all columns in pandas

In [11]:
columns_list = match_df.columns
columns_list

Index(['Team', 'Goals', 'Shots on target', 'Shots off target',
       'Shooting Accuracy', '% Goals-to-shots', 'Total shots (inc. Blocked)',
       'Hit Woodwork', 'Penalty goals', 'Penalties not scored', 'Headed goals',
       'Passes', 'Passes completed', 'Passing Accuracy', 'Touches', 'Crosses',
       'Dribbles', 'Corners Taken', 'Tackles', 'Clearances', 'Interceptions',
       'Clearances off line', 'Clean Sheets', 'Blocks', 'Goals conceded',
       'Saves made', 'Saves-to-shots ratio', 'Fouls Won', 'Fouls Conceded',
       'Offsides', 'Yellow Cards', 'Red Cards', 'Subs on', 'Subs off',
       'Players Used'],
      dtype='object')

In [14]:
Sales_df=pd.read_csv(filepath_or_buffer="Sales Transactions-2017.csv")
Sales_df

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2017,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00",NaN,"13,100.00"
1,1/4/2017,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
2,1/4/2017,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23,"11,500.00",NaN,"30,990.00"
3,1/4/2017,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
4,1/4/2017,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00","8,450.00",NaN,NaN
...,...,...,...,...,...,...,...,...,...
47285,31/03/2018,Sal:10042,Vkp,10*10 SHEET,25,137,"3,425.00",NaN,"3,425.00"
47286,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47287,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47288,NaN,Total,NaN,NaN,"607,734.60","669,300.49","9,953,816.13","106,607.00","9,868,583.13"
47289,NaN,Total,NaN,NaN,"7,593,062.00","8,309,116.00","115,778,725.71","936,348.00","115,105,123.71"

## How to check all columns in pandas

In [15]:
columns_list = Sales_df.columns
columns_list

Index(['Date', 'Voucher', 'Party', 'Product', 'Qty', 'Rate', 'Gross', 'Disc',
       'Voucher Amount'],
      dtype='object')